version: '3.8'
services:
  postgres:
    image: nickblah/postgis
    shm_size: 1g
    restart: always
    environment:
      POSTGRES_USER: 'myuser'
      POSTGRES_PASSWORD: 'mypassword'
      POSTGRES_DB: 'club'
    volumes:
      - club:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
  db_test:
    image: nickblah/postgis
    environment:
      POSTGRES_USER: test_myuser
      POSTGRES_PASSWORD: test_mypassword
      POSTGRES_DB: test_club
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5433:5432'

volumes:
  club:
    driver: local
